// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBip2mWeQh4XATeqcxlkGfHuXvcLbdn5qo',
    appId: '1:478777580396:web:a0598e2e946a8f9643b149',
    messagingSenderId: '478777580396',
    projectId: 'smart-lathe-monitoring',
    authDomain: 'smart-lathe-monitoring.firebaseapp.com',
    storageBucket: 'smart-lathe-monitoring.firebasestorage.app',
    measurementId: 'G-B2DQFCZV2D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi0egym6yL4BsqTrNiAPJm1M2Hz7v1eBs',
    appId: '1:478777580396:android:fb9ff2cbae340d9643b149',
    messagingSenderId: '478777580396',
    projectId: 'smart-lathe-monitoring',
    storageBucket: 'smart-lathe-monitoring.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIOE60TRwoUaTRiiH7kNmBCEjgwjF4tSo',
    appId: '1:478777580396:ios:8b7a784e5512651643b149',
    messagingSenderId: '478777580396',
    projectId: 'smart-lathe-monitoring',
    storageBucket: 'smart-lathe-monitoring.firebasestorage.app',
    iosBundleId: 'com.example.smartLatheFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIOE60TRwoUaTRiiH7kNmBCEjgwjF4tSo',
    appId: '1:478777580396:ios:8b7a784e5512651643b149',
    messagingSenderId: '478777580396',
    projectId: 'smart-lathe-monitoring',
    storageBucket: 'smart-lathe-monitoring.firebasestorage.app',
    iosBundleId: 'com.example.smartLatheFrontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBip2mWeQh4XATeqcxlkGfHuXvcLbdn5qo',
    appId: '1:478777580396:web:f03f31b01b8f2bef43b149',
    messagingSenderId: '478777580396',
    projectId: 'smart-lathe-monitoring',
    authDomain: 'smart-lathe-monitoring.firebaseapp.com',
    storageBucket: 'smart-lathe-monitoring.firebasestorage.app',
    measurementId: 'G-ELDVZBK0BK',
  );
}
